name: Maven Deploy

on:
  push:
    branches:
      - 'main' # Build the latest develop-SNAPSHOT
    paths:
      - '**/src/**'
      - '**/pom.xml'
      - 'pom.xml'
      
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  INSTRUCTOR_USER: "instructor_e2e"
  INSTRUCTOR_PASSWORD: ${{ secrets.INSTRUCTOR_PASSWORD }}
  STUDENT_USER: "student_e2e"
  ARTEMIS_URL: "https://artemis-test.sdq.kastel.kit.edu"
  COURSE_ID: "4"
  PROGRAMMING_EXERCISE_ID: "41"

jobs:
  publish:
    uses: kit-sdq/actions/.github/workflows/maven.yml@main
    with:
      deploy: true
    secrets:
      OSSRH_USER: ${{secrets.OSSRH_USER}}
      OSSRH_TOKEN: ${{secrets.OSSRH_TOKEN}}
      GPG_KEY: ${{secrets.GPG_KEY}}

